on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: demoaks1.azurecr.io
        username: ${{ secrets.acr_demoaks1_username }}
        password: ${{ secrets.acr_demoaks1_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t demoaks1.azurecr.io/sampleaks:${{ github.sha }}
        docker push demoaks1.azurecr.io/sampleaks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_sampleaks_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep sampleaks69b2 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace sampleaks69b2`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: sampleaks69b2
        container-registry-url: demoaks1.azurecr.io
        container-registry-username: ${{ secrets.acr_demoaks1_username }}
        container-registry-password: ${{ secrets.acr_demoaks1_password }}
        secret-name: sampleaksdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: sampleaks69b2
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          demoaks1.azurecr.io/sampleaks:${{ github.sha }}
        imagepullsecrets: |
          sampleaksdockerauth